### ISSUE TITLE
RFE: Please support Python 3

### ISSUE THREAD

**Issue by pcfe** [jbretsch/pvrutils#1]
Could you please upgrade the clean script to also support Python 3?

Background:
Thank you for creating `cleanup.py`, it has been very useful on my Dreambox (with vendor image) for may years now.
But, my DM900 is currently being decommissioned (display broken) in favour of a more powerful box that runs OpenBh 5.0.
On that distro, while I welcome the transition to Python 3 (seeing how long py2 has been EOL), `cleanup.py` now errors out with a syntax error.

```bash
root@vuduo4kse:~# ./bin/cleanup.py 
  File "/home/root/./bin/cleanup.py", line 15
    print '''
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(''')?
root@vuduo4kse:~# head -n 1 ./bin/cleanup.py
#!/usr/bin/python
root@vuduo4kse:~# /usr/bin/python --version
Python 3.9.7
root@vuduo4kse:~# ls -l /usr/bin/python*
lrwxrwxrwx    1 root     root             7 Jan  1  1970 /usr/bin/python -> python3
lrwxrwxrwx    1 root     root             9 Jan  1  1970 /usr/bin/python3 -> python3.9
-rwxr-xr-x    1 root     root          5544 Feb 13 22:56 /usr/bin/python3.9
root@vuduo4kse:~# cat /etc/os-release 
ID=openbh
NAME="openbh"
VERSION="5.0"
VERSION_ID=5.0
PRETTY_NAME="openbh 5.0"
```

**Comment by pcfe** [comment]
My attempt 6a786cb56fca25a6117096d2a4f3056b518d29fb is sadly not enough, so much for _I have little idea of python but I can add parentheses_ :-(

```bash
root@vuduo4kse:~/bin# ./cleanup.py -s 680000 /media/hdd/movie/autoclean
You requested to have 680000 MB available in the following directories:
/media/hdd/movie/autoclean
Traceback (most recent call last):
  File "/home/root/bin/./cleanup.py", line 315, in <module>
    sys.exit(main())
  File "/home/root/bin/./cleanup.py", line 296, in main
    cleanup(directories, min_avail_space)
  File "/home/root/bin/./cleanup.py", line 159, in cleanup
    all_files = find_files_sorted_by_mtime(directories)
  File "/home/root/bin/./cleanup.py", line 125, in find_files_sorted_by_mtime
    os.path.walk(directory, process_dir, files)
AttributeError: module 'posixpath' has no attribute 'walk'
```

**Comment by jbretsch** [comment]
Hey @pcfe,

I am happy to hear that this little script has been of use to you.

With 4bc9eaf31f3e345bda4c7049792844524944e960 which I have just added to the `master` branch, it should work with Python 2 and 3.

Does the new version work for you?

**Comment by pcfe** [comment]
> Does the new version work for you?

Yes, works great with 4bc9eaf31f3e345bda4c7049792844524944e960 on my
Python 3 box.
Thank you very much.

pcfe
